### ISSUE TITLE
tmux-fzf doesn't work if ...

### ISSUE THREAD

**Issue by lloydngnn** [sainnhe/tmux-fzf#41]
I'm using bash + tmux + tpm + 'tmux-fzf' plugin for tmux and I'm using 'oh my tmux' repo for tmux configuration files (.tmux.conf and .tmux.conf.local)
If I put 'list of plugins' scripts into .tmux.conf =====> tmux-fzf works
If I put 'list of plugins' scripts into .tmux.conf.local => tmux-fzf doesn't work

Here is my tpm scripts added to the bottom of my .tmux.conf.local file:
`
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.dotfiles/tmux/plugins'
`
`# ***** list of plugins *****`
`set -g @plugin 'tmux-plugins/tpm'`
`set -g @plugin 'tmux-plugins/tmux-sensible'`
`set -g @plugin 'sainnhe/tmux-fzf'`
`# ***** end: list of plugins *****`
`run '~/.dotfiles/tmux/plugins/tpm/tpm'`

**Comment by sainnhe** [comment]
1. Tmux only supports `.tmux.conf` as configuration file, the `.tmux.conf.local` is something that will only be used in oh my tmux. So if this plugin works in `.tmux.conf` but doesn't work in `.tmux.conf.local`, you should obviously open an issue in oh my tmux instead of in this repository.
2. Are you sure this configuration will install any plugins? I saw this in the definition of `.tmux.conf.local`:

https://github.com/gpakosz/.tmux/blob/1f91646af104ed423054a1dd47a3b8c7ae69cfbc/.tmux.conf.local#L370

**Comment by sainnhe** [comment]
Closed since this is nothing to do with this plugin.

**Comment by lloydngnn** [comment]
Oh! Thank you
