### ISSUE TITLE
Conflict with 'tmux-plugins/tmux-resurrect' 

### ISSUE THREAD

**Issue by draibolit** [sainnhe/tmux-fzf#46]
It worked well when I initiated the new tmux server but I couldn't activate the when tmux was reloaded from 'tmux-plugins/tmux-resurrect'

I'm using tmux 3.2a.

Updates:
It showed menu when I ran `~/.tmux/plugins/tmux-fzf/main.sh` from shell
but tmux command `:run-shell -b ~/.tmux/plugins/tmux-fzf/main.sh` didn't work

**Comment by sainnhe** [comment]
If it works fine in a new tmux environment, it means this plugin behaves as expected.

If things are different in new tmux environment and tmux-resurrect initiated environment, it means there's something wrong in tmux-resurrect.

You should open this issue in tmux-resurrect, not here.

**Comment by ll-nick** [comment]
In case someone else stumbles over this:

I had the same issue due to the fact that the tmux-resurrect environment did not know about fzf which likely happens if you did not install fzf via a package manager and the PATH variable needs to be adjusted.

I fixed it using [this answer](https://stackoverflow.com/questions/8645053/how-do-i-start-tmux-with-my-current-environment#comment23100473_8645053) and adding
`set-option -ga update-environment ' PATH'`
to my tmux.conf.
